version: "3.7"
services:
  swagger-codegen-corporateclient:
    build: .
    volumes:
      - ./corporateclient:/swagger # ローカルのswaggerディレクトリをコンテナのswaggerディレクトリにマウント
  swagger-codegen-webhookclient:
    build: .
    volumes:
      - ./webhookclient:/swagger # ローカルのswaggerディレクトリをコンテナのswaggerディレクトリにマウント
